### ISSUE TITLE
Broken link in README (Todo List App)

### ISSUE THREAD

**Issue by evgeniy-scherbina** [TBD54566975/incubating-web5-labs#36]
Broken link in README (Todo List App):

Build and then install the web5-wallet into chrome, follow the instructions [here](https://github.com/TBD54566975/incubating-web5-labs/blob/main/todo-app/web5-wallet/README.md)

**Comment by ALRubinger** [comment]
Thanks for reporting! As we're prepping for a release of this, found the `README` no longer references the link you're mentioning; closing this out. 🤘🏻
