### ISSUE TITLE
Uncaught (in promise) UNKNOWN_METHOD (Todo List App)

### ISSUE THREAD

**Issue by evgeniy-scherbina** [TBD54566975/incubating-web5-labs#37]
I've encountered such error during app launch: `Uncaught (in promise) UNKNOWN_METHOD`

Promise.catch (async) |   |  
-- | -- | --
  | callWithAsyncErrorHandling | @ | runtime-core.esm-bundler.js:168
  | hook.__weh.hook.__weh | @ | runtime-core.esm-bundler.js:2713
  | flushPostFlushCbs | @ | runtime-core.esm-bundler.js:343
  | render2 | @ | runtime-core.esm-bundler.js:6263
  | mount | @ | runtime-core.esm-bundler.js:4456
  | app.mount | @ | runtime-dom.esm-bundler.js:1607
  | (anonymous) | @ | main.js:11

could you pls. help me?

I've installed `Web5 Wallet extension` and authorized (Todo List App)

**Comment by evgeniy-scherbina** [comment]
Seems resolved initially I used this: https://github.com/TBD54566975/web5-wallet-browser instead of this: https://github.com/TBD54566975/incubating-web5-labs/tree/main/web5-wallet

**Comment by ALRubinger** [comment]
Thank you! Because this is moved to legacy and the current version in `main` and tagged `0.1.0` no longer has this, I'll resolve. Appreciate ya!
