### ISSUE TITLE
Update ToDo app to use v 0.6.x

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/incubating-web5-labs#47]
Source of truth for this work is in `upstream` branch `issue-47/update-sdk`, reflected in Draft PR #55.

Dependencies still needed to close this out:

* #51 
* #54

**Comment by ALRubinger** [comment]
Current draft PR for this work is #55 in `upstream` branch `issue-47/update-sdk`. There are issues noted in the draft PR which need addressing to close this out:

* #51 
* #54
